apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyimg1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pyimg1
  template:
    metadata:
      labels:
        run: pyimg1
    spec:
      containers:
      - name: pyimg1
        image: gcr.io/docker-project-0502/pyimg1:latest
        ports:
        - containerPort: 8080
#         command:
#        - sh
#        - -c
#        - while true; do sleep 1; done

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pyimg1
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: pyimg1
#   template:
#     metadata:
#       labels:
#         app: pyimg1
#     spec:
#       containers:
#       - name: pyimg1
#         image: gcr.io/docker-project-0502/pyimg1:latest
#         ports:
#         - containerPort: 8080
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: 80
#           initialDelaySeconds: 10
#           periodSeconds: 30
#           failureThreshold: 3
#         readinessProbe:
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 5
#           periodSeconds: 10
#           failureThreshold: 3
#         lifecycle:
#           preStop:
#             exec:
#               command: ["/bin/sh", "-c", "kill 1"]
