apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pyimg1
  name: pyimg1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pyimg1
  template:
    metadata:
      labels:
        run: pyimg1
    spec:
      containers:
      - image: gcr.io/docker-project-0502/pyimg1:latest
        name: pyimg1
        ports:
        - containerPort: 80
