apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyimg1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyimg1
#   minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pyimg1
    spec:
      containers:
      - name: pyimg1
        image: gcr.io/docker-project-0502/pyimg1:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
