apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: automation_app
  name: automation_app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: automation_app
  template:
    metadata:
      labels:
        run: automation_app
    spec:
      containers:
      - image: gcr.io/docker-project-0502/automation_app:latest
        name: automation_app
        ports:
        - containerPort: 80
