apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyimg1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyimg1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pyimg1
    spec:
      containers:
      - name: pyimg1
#         image: gcr.io/docker-project-0502/pyimg1:latest
        image: gcr.io/docker-project-0502/pyimg1@sha256:2a52df25b7bf6c996dc59974b24215e84e3caabbe6afc3254feae0ff69a9dadb
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 250m
            ephemeral-storage: 500Mi
            memory: 1Gi
        ports:
        - containerPort: 80
