apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyimg1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyimg1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pyimg1
    spec:
      containers:
      - name: pyimg1
        image: gcr.io/docker-project-0502/pyimg1:latest
#         resources:
#           limits:
#             cpu: 1GiB
#             ephemeral-storage: 1GiB
#             memory: 2GiB
#           requests:
#             cpu: 1GiB
#             ephemeral-storage: 1GiB
#             memory: 1GiB
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 4GiB
            memory: 2.5Gi
          requests:
            cpu: 2GiB
            memory: 1.5Gi
