apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: $_APP_NAME
  name: $_APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      run: $_APP_NAME
  template:
    metadata:
      labels:
        run: $_APP_NAME
    spec:
      containers:
      - image: gcr.io/$_PROJECT_ID/$_APP_NAME:latest
        name: $_APP_NAME
        ports:
        - containerPort: _CONTAINER_PORT
